// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBz_I6TrfnV4Su6TTWT4yJelpmUnIMq5s',
    appId: '1:845303370991:web:0ecc491e000b74cca0b71a',
    messagingSenderId: '845303370991',
    projectId: 'test-loging-200a3',
    authDomain: 'test-loging-200a3.firebaseapp.com',
    storageBucket: 'test-loging-200a3.firebasestorage.app',
    measurementId: 'G-7B7MX7JXZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvtcQ0x2Q_yuW-4XqLsi1i1HCVFDb-nu0',
    appId: '1:845303370991:android:0cca7dde746db52da0b71a',
    messagingSenderId: '845303370991',
    projectId: 'test-loging-200a3',
    storageBucket: 'test-loging-200a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1FVBjoUj3iSmkBVyN57ePFnlpvOFQkFY',
    appId: '1:845303370991:ios:118da593138ccffca0b71a',
    messagingSenderId: '845303370991',
    projectId: 'test-loging-200a3',
    storageBucket: 'test-loging-200a3.firebasestorage.app',
    iosBundleId: 'com.example.appMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1FVBjoUj3iSmkBVyN57ePFnlpvOFQkFY',
    appId: '1:845303370991:ios:118da593138ccffca0b71a',
    messagingSenderId: '845303370991',
    projectId: 'test-loging-200a3',
    storageBucket: 'test-loging-200a3.firebasestorage.app',
    iosBundleId: 'com.example.appMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBz_I6TrfnV4Su6TTWT4yJelpmUnIMq5s',
    appId: '1:845303370991:web:c1e5094b993a444ea0b71a',
    messagingSenderId: '845303370991',
    projectId: 'test-loging-200a3',
    authDomain: 'test-loging-200a3.firebaseapp.com',
    storageBucket: 'test-loging-200a3.firebasestorage.app',
    measurementId: 'G-M2XFXN6Q1F',
  );
}
